version: '3.9'

services:
  mg-mysql:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testbackend
  mg-backend:
    build: .
    ports:
      - "8080:8080"
